'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

// Tipos de idiomas soportados
export type Language = 'es' | 'ro';

// Interfaz del contexto
interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Traducciones
const translations: Record<Language, Record<string, string>> = {
  es: {
    // Navegación
    'nav.home': 'Inicio',
    'nav.search': 'Buscar',
    'nav.publish': 'Publicar',
    'nav.messages': 'Mensajes',
    'nav.profile': 'Perfil',
    'nav.login': 'Iniciar sesión',
    'nav.register': 'Registrarse',
    'nav.logout': 'Cerrar sesión',
    'nav.favorites': 'Favoritos',
    'nav.notifications': 'Notificaciones',
    'nav.settings': 'Ajustes',
    'nav.help': 'Ayuda',
    
    // Página principal
    'home.hero.title': '¿Qué estás buscando hoy?',
    'home.hero.subtitle': 'Miles de anuncios cerca de ti',
    'home.search.placeholder': 'Buscar coches, móviles, pisos...',
    'home.search.button': 'Buscar',
    'home.categories': 'Categorías',
    'home.featured': 'Destacados',
    'home.recent': 'Más recientes',
    'home.viewAll': 'Ver todos',
    'home.publishFree': 'Publica gratis',
    
    // Categorías
    'category.imobiliare': 'Inmobiliaria',
    'category.auto_moto': 'Auto moto',
    'category.locuri_de_munca': 'Empleo',
    'category.matrimoniale': 'Contactos',
    'category.servicii': 'Servicios',
    'category.electronice': 'Electrónica',
    'category.moda_accesorii': 'Moda y accesorios',
    'category.animale': 'Animales',
    'category.casa_gradina': 'Casa y jardín',
    'category.timp_liber_sport': 'Ocio y deporte',
    'category.mama_copil': 'Bebés y niños',
    'category.cazare_turism': 'Turismo',
    'category.otros': 'Otros',
    
    // Anuncios
    'ad.price': 'Precio',
    'ad.negotiable': 'Negociable',
    'ad.location': 'Ubicación',
    'ad.published': 'Publicado',
    'ad.views': 'Vistas',
    'ad.contact': 'Contactar',
    'ad.sendMessage': 'Enviar mensaje',
    'ad.call': 'Llamar',
    'ad.share': 'Compartir',
    'ad.report': 'Reportar',
    'ad.favorite': 'Favorito',
    'ad.description': 'Descripción',
    'ad.details': 'Detalles',
    'ad.seller': 'Vendedor',
    'ad.condition': 'Estado',
    'ad.condition.new': 'Nuevo',
    'ad.condition.likeNew': 'Seminuevo',
    'ad.condition.used': 'Usado',
    'ad.delivery': 'Envío disponible',
    'ad.inPerson': 'Venta en persona',
    'ad.promoted': 'Promocionado',
    'ad.featured': 'Destacado',
    'ad.premium': 'Premium',
    'ad.vip': 'VIP',
    
    // Publicar
    'publish.title': 'Publicar anuncio',
    'publish.titleField': 'Título del anuncio',
    'publish.titlePlaceholder': 'Ej: iPhone 15 Pro Max 256GB',
    'publish.description': 'Descripción',
    'publish.descriptionPlaceholder': 'Describe tu producto con detalle...',
    'publish.price': 'Precio',
    'publish.pricePlaceholder': 'Precio en €',
    'publish.category': 'Categoría',
    'publish.selectCategory': 'Selecciona una categoría',
    'publish.location': 'Ubicación',
    'publish.locationPlaceholder': 'Ciudad o código postal',
    'publish.photos': 'Fotos',
    'publish.addPhotos': 'Añadir fotos',
    'publish.maxPhotos': 'Máximo 10 fotos',
    'publish.condition': 'Estado del producto',
    'publish.submit': 'Publicar anuncio',
    'publish.saving': 'Publicando...',
    'publish.success': '¡Anuncio publicado con éxito!',
    'publish.error': 'Error al publicar el anuncio',
    
    // Perfil
    'profile.myProfile': 'Mi perfil',
    'profile.myAds': 'Mis anuncios',
    'profile.promotions': 'Promociones',
    'profile.favorites': 'Favoritos',
    'profile.messages': 'Mensajes',
    'profile.invoices': 'Facturas',
    'profile.settings': 'Ajustes',
    'profile.edit': 'Editar perfil',
    'profile.save': 'Guardar',
    'profile.cancel': 'Cancelar',
    'profile.memberSince': 'Miembro desde',
    'profile.verified': 'Verificado',
    'profile.rating': 'Valoración',
    'profile.activeAds': 'Anuncios activos',
    'profile.totalViews': 'Vistas totales',
    'profile.totalFavorites': 'Favoritos totales',
    'profile.noPlan': 'Sin plan activo',
    'profile.clickForPlans': 'Haz clic para ver planes',
    'profile.personalData': 'Datos Personales',
    'profile.name': 'Nombre',
    'profile.phone': 'Teléfono',
    'profile.location': 'Ubicación',
    'profile.notSpecified': 'No especificado',
    'profile.notSpecifiedF': 'No especificada',
    'profile.activePromotions': 'Mis Promociones Activas',
    'profile.daysRemaining': 'restantes',
    'profile.security': 'Seguridad',
    'profile.emailVerified': 'Email verificado',
    'profile.active': 'Activo',
    'profile.activate': 'Activar',
    'profile.noActivePromotions': 'No tienes promociones activas',
    'profile.promoteForVisibility': 'Promociona tus anuncios para más visibilidad',
    'profile.viewAll': 'Ver todas',
    'profile.featured': 'Destacado',
    'profile.myAccount': 'Mi Cuenta',
    'profile.manageAccount': 'Gestiona tu cuenta, créditos y planes de promoción',
    'profile.myAdsTitle': 'Mis Anuncios',
    'profile.published': 'publicados',
    'profile.manageAds': 'Gestiona y promociona tus anuncios publicados',
    'profile.myFavorites': 'Mis Favoritos',
    'profile.saved': 'guardados',
    'profile.savedForLater': 'Tus anuncios guardados para ver más tarde',
    'profile.myPromotions': 'Mis Promociones',
    'profile.managePromotions': 'Gestiona tus promociones activas y potencia tus anuncios',
    'profile.rechargeCredits': 'Recargar Créditos',
    'profile.newAd': 'Nuevo anuncio',
    'profile.promoteAd': 'Promocionar Anuncio',
    'profile.ads': 'Anuncios',
    'profile.views': 'Vistas',
    'profile.myBalance': 'Mi Saldo',
    'profile.available': 'Disponible',
    'profile.planType': 'Plan',
    'profile.available2': 'disponibles',
    'profile.businessAccount': 'Cuenta Empresa',
    'profile.total': 'Total',
    'profile.promoted': 'Promocionados',
    'profile.adsFound': 'anuncios encontrados',
    'profile.moreViews': 'Más vistas',
    'profile.totalSaved': 'Total guardados',
    'profile.totalInvoices': 'Total facturas',
    'profile.totalBilled': 'Total facturado',
    'profile.invoicesTotal': 'facturas en total',
    'profile.invoice': 'factura',
    'profile.totalClaimed': 'Total reclamado',
    'profile.totalPromotions': 'Total Promociones',
    'profile.totalInvestment': 'Inversión Total',
    'profile.avgIncrease': 'Promedio Incremento',
    'profile.promotionStats': 'Estadísticas de promociones',
    'profile.promotionStatsTitle': 'Estadísticas de la Promoción',
    'profile.faster': 'Más rápido',
    'profile.successRate': 'Tasa éxito',
    'profile.daysLeft': 'Días restantes',
    'profile.increase': 'Incremento',
    'profile.sales': 'Ventas',
    'profile.promotedAds': 'anuncios promocionados tienen un rendimiento superior',
    'profile.myPromotedAds': 'Mis Anuncios Promovidos',
    'profile.activePromotion': 'promoción activa',
    'profile.activePromotionsPlural': 'promociones activas',
    'profile.ad': 'Anuncio',
    'profile.plan': 'Plan',
    'profile.duration': 'Duración',
    'profile.performance': 'Rendimiento',
    'profile.status': 'Estado',
    'profile.actions': 'Acciones',
    'profile.viewsCount': 'visualizaciones',
    'profile.daysRemainingTable': 'días restantes',
    'profile.activeStatus': 'Activo',
    'profile.viewDetails': 'Ver Detalles',
    'profile.noTitle': 'Sin título',
    'profile.noCategory': 'Sin categoría',
    'profile.adsCount': 'anuncios',
    'profile.adCount': 'anuncio',
    'profile.noPromotedAdsYet': 'Aún no tienes anuncios promovidos',
    'profile.promoteAdsDescription': 'Promociona tus anuncios para que aparezcan en las primeras posiciones y llegues a más compradores',
    'profile.promotionDetails': 'Detalles de la Promoción',
    'profile.planTypeLabel': 'Tipo de plan',
    'profile.activationDate': 'Fecha de activación',
    'profile.expirationDate': 'Fecha de expiración',
    'profile.totalDuration': 'Duración total',
    'profile.days': 'días',
    'profile.searchPriority': 'Prioridad en búsquedas',
    'profile.maximum': 'Máxima',
    'profile.high': 'Alta',
    'profile.medium': 'Media',
    'profile.visibilityBoost': 'Boost de visibilidad',
    'profile.activeBenefits': 'Beneficios Activos',
    'profile.firstPosition': 'Primera posición en resultados',
    'profile.vipLabel': 'Etiqueta VIP destacada',
    'profile.mainCarousel': 'Aparece en carrusel principal',
    'profile.notifyInterested': 'Notificación a interesados',
    'profile.top5Results': 'Top 5 en resultados',
    'profile.premiumLabel': 'Etiqueta Premium',
    'profile.moreVisibility': 'Mayor visibilidad',
    'profile.featuredInCategory': 'Destacado en categoría',
    'profile.featuredLabel': 'Etiqueta Destacado',
    'profile.viewAd': 'Ver Anuncio',
    'profile.close': 'Cerrar',
    'profile.price': 'Precio',
    'profile.noPromotion': 'Sin promoción',
    'profile.paused': 'Pausado',
    'profile.inReview': 'En revisión',
    'profile.editAction': 'Editar',
    'profile.viewAction': 'Ver',
    'profile.deleteAction': 'Eliminar',
    'profile.promoteAction': 'Promocionar',
    'profile.confirmDelete': '¿Estás seguro de que quieres eliminar este anuncio? Esta acción no se puede deshacer.',
    'profile.adDeleted': 'Anuncio eliminado',
    'profile.adDeletedDesc': 'El anuncio ha sido eliminado correctamente',
    'profile.errorDeleting': 'No se pudo eliminar el anuncio',
    'profile.recentlyAdded': 'Añadidos recientemente',
    'profile.categories': 'Categorías',
    'profile.searchFavorites': 'Buscar en favoritos...',
    'profile.loadingFavorites': 'Cargando favoritos...',
    'profile.noFavoritesYet': 'Aún no tienes favoritos',
    'profile.noFavoritesDesc': 'Guarda tus anuncios favoritos para encontrarlos fácilmente más tarde. Haz clic en el corazón de cualquier anuncio para agregarlo aquí.',
    'profile.exploreAds': 'Explorar anuncios',
    'profile.noResults': 'No se encontraron resultados',
    'profile.noResultsFor': 'No hay anuncios que coincidan con',
    'profile.clearSearch': 'Limpiar búsqueda',
    'profile.inPersonSale': 'Venta en persona',
    'profile.recent': 'Reciente',
    'profile.myInvoices': 'Mis Facturas',
    'profile.paymentHistory': 'Historial de pagos y facturas',
    'profile.invoiceNumber': 'Nº Factura',
    'profile.date': 'Fecha',
    'profile.concept': 'Concepto',
    'profile.totalAmount': 'Total',
    'profile.paid': 'Pagada',
    'profile.pending': 'Pendiente',
    'profile.cancelled': 'Cancelada',
    'profile.viewInvoice': 'Ver factura',
    'profile.downloadPdf': 'Descargar PDF',
    'profile.noInvoices': 'No tienes facturas',
    'profile.noInvoicesDesc': 'Cuando compres un plan de promoción, tus facturas aparecerán aquí y podrás descargarlas en PDF.',
    'profile.vatIncluded': 'IVA incluido',
    'profile.invoicesInTotal': 'facturas en total',
    'profile.invoiceInTotal': 'factura en total',
    
    // Ajustes
    'settings.title': 'Ajustes',
    'settings.account': 'Cuenta',
    'settings.notifications': 'Notificaciones',
    'settings.privacy': 'Privacidad',
    'settings.security': 'Seguridad',
    'settings.appearance': 'Apariencia',
    'settings.help': 'Ayuda',
    'settings.personalInfo': 'Información personal',
    'settings.updateInfo': 'Actualiza tu información básica',
    'settings.fullName': 'Nombre completo',
    'settings.email': 'Email',
    'settings.phone': 'Teléfono',
    'settings.location': 'Ubicación',
    'settings.companyData': 'Datos de empresa',
    'settings.commercialName': 'Nombre comercial',
    'settings.cif': 'CIF/NIF',
    'settings.fiscalAddress': 'Dirección fiscal',
    'settings.website': 'Sitio web',
    'settings.schedule': 'Horario de atención',
    'settings.companyDescription': 'Descripción de la empresa',
    'settings.dangerZone': 'Zona de peligro',
    'settings.deleteAccount': 'Eliminar cuenta',
    'settings.deleteWarning': 'Esta acción eliminará todos tus datos permanentemente',
    'settings.changePassword': 'Cambiar contraseña',
    'settings.currentPassword': 'Contraseña actual',
    'settings.newPassword': 'Nueva contraseña',
    'settings.confirmPassword': 'Confirmar contraseña',
    'settings.language': 'Idioma',
    'settings.theme': 'Tema',
    'settings.themeLight': 'Claro',
    'settings.themeDark': 'Oscuro',
    'settings.themeSystem': 'Sistema',
    'settings.manageAccount': 'Gestiona tu cuenta y preferencias',
    'settings.logout': 'Cerrar sesión',
    'settings.emailNotChange': 'El email no se puede cambiar',
    'settings.yourName': 'Tu nombre',
    'settings.yourPhone': 'Tu teléfono',
    'settings.yourCity': 'Tu ciudad',
    'settings.irreversibleActions': 'Acciones irreversibles',
    'settings.delete': 'Eliminar',
    'settings.loadingSettings': 'Cargando ajustes...',
    'settings.redirectingLogin': 'Redirigiendo al login...',
    'settings.saved': 'Guardado',
    'settings.save': 'Guardar',
    'settings.businessInfo': 'Información comercial de tu negocio',
    'settings.companyName': 'Nombre de tu empresa',
    'settings.emailNotifications': 'Notificaciones por email',
    'settings.chooseEmails': 'Elige qué emails quieres recibir',
    'settings.newMessages': 'Mensajes nuevos',
    'settings.newMessagesDesc': 'Recibe un email cuando alguien te envíe un mensaje',
    'settings.favoritesNotif': 'Favoritos',
    'settings.favoritesNotifDesc': 'Notificaciones sobre cambios en tus anuncios favoritos',
    'settings.promotionsNews': 'Promociones y novedades',
    'settings.promotionsNewsDesc': 'Ofertas especiales y actualizaciones de VINDEL',
    'settings.pushNotifications': 'Notificaciones push',
    'settings.pushDesc': 'Notificaciones en tu dispositivo',
    'settings.messages': 'Mensajes',
    'settings.instantNotif': 'Notificaciones instantáneas de nuevos mensajes',
    'settings.favoritesActivity': 'Actividad en favoritos',
    'settings.priceAlerts': 'Alertas de bajadas de precio y cambios',
    'settings.sounds': 'Sonidos',
    'settings.soundsNotif': 'Sonidos de notificación',
    'settings.soundsNotifDesc': 'Reproduce un sonido al recibir notificaciones',
    'settings.profileVisibility': 'Visibilidad del perfil',
    'settings.controlInfo': 'Controla qué información pueden ver otros usuarios',
    'settings.publicProfile': 'Perfil público',
    'settings.publicProfileDesc': 'Permite que otros usuarios vean tu perfil',
    'settings.showPhone': 'Mostrar teléfono',
    'settings.showPhoneDesc': 'Muestra tu número de teléfono en tus anuncios',
    'settings.showLocation': 'Mostrar ubicación',
    'settings.showLocationDesc': 'Muestra tu ciudad en tu perfil',
    'settings.showStats': 'Mostrar estadísticas',
    'settings.showStatsDesc': 'Muestra tus estadísticas de ventas públicamente',
    'settings.yourData': 'Tus datos',
    'settings.downloadData': 'Descargar mis datos',
    'settings.downloadDataDesc': 'Obtén una copia de toda tu información',
    'settings.download': 'Descargar',
    'settings.password': 'Contraseña',
    'settings.changePasswordDesc': 'Actualiza tu contraseña regularmente para mayor seguridad',
    'settings.change': 'Cambiar',
    'settings.twoFactor': 'Verificación en dos pasos',
    'settings.twoFactorAuth': 'Autenticación 2FA',
    'settings.twoFactorDesc': 'Añade una capa extra de seguridad a tu cuenta',
    'settings.activate': 'Activar',
    'settings.activeSessions': 'Sesiones activas',
    'settings.thisDevice': 'Este dispositivo',
    'settings.lastActivity': 'Última actividad: ahora',
    'settings.active': 'Activo',
    'settings.themeTitle': 'Tema',
    'settings.themeDesc': 'Selecciona la apariencia de la aplicación',
    'settings.light': 'Claro',
    'settings.dark': 'Oscuro',
    'settings.system': 'Sistema',
    'settings.designStyle': 'Estilo de Diseño',
    'settings.designStyleDesc': 'Elige el estilo visual de toda la web',
    'settings.cardStyle': 'Estilo de Tarjetas',
    'settings.designTip': 'El estilo de diseño cambia la apariencia de las tarjetas, categorías y elementos visuales de toda la web.',
    'settings.languageDesc': 'Selecciona tu idioma preferido',
    'settings.helpCenter': 'Centro de ayuda',
    'settings.faq': 'Preguntas frecuentes',
    'settings.faqDesc': 'Encuentra respuestas a las preguntas más comunes',
    'settings.guides': 'Guías y tutoriales',
    'settings.guidesDesc': 'Aprende a sacar el máximo provecho de VINDEL',
    'settings.contactSupport': 'Contactar soporte',
    'settings.contactSupportDesc': '¿Necesitas ayuda? Escríbenos',
    'settings.privacyPolicy': 'Políticas de privacidad',
    'settings.privacyPolicyDesc': 'Conoce cómo protegemos tus datos',
    'settings.terms': 'Términos y condiciones',
    'settings.termsDesc': 'Lee nuestros términos de servicio',
    'settings.needHelp': '¿Necesitas ayuda?',
    'settings.teamAvailable': 'Nuestro equipo está disponible 24/7 para ayudarte',
    'settings.chatNow': 'Chatear ahora',
    'settings.deleteAccountQuestion': '¿Eliminar cuenta?',
    'settings.deleteAccountWarning': 'Esta acción es irreversible. Se eliminarán todos tus anuncios, mensajes y datos personales.',
    'settings.cancel': 'Cancelar',
    'settings.changePasswordTitle': 'Cambiar contraseña',
    'settings.changePasswordSubtitle': 'Introduce tu contraseña actual y la nueva',
    'settings.passwordUpdated': '¡Contraseña actualizada!',
    'settings.updatePassword': 'Actualizar contraseña',
    
    // Mensajes
    'messages.title': 'Mensajes',
    'messages.noMessages': 'No tienes mensajes',
    'messages.startConversation': 'Inicia una conversación',
    'messages.typeMessage': 'Escribe un mensaje...',
    'messages.send': 'Enviar',
    'messages.online': 'En línea',
    'messages.offline': 'Desconectado',
    'messages.lastSeen': 'Última vez',
    
    // Autenticación
    'auth.login': 'Iniciar sesión',
    'auth.register': 'Registrarse',
    'auth.email': 'Correo electrónico',
    'auth.password': 'Contraseña',
    'auth.confirmPassword': 'Confirmar contraseña',
    'auth.forgotPassword': '¿Olvidaste tu contraseña?',
    'auth.noAccount': '¿No tienes cuenta?',
    'auth.hasAccount': '¿Ya tienes cuenta?',
    'auth.createAccount': 'Crear cuenta',
    'auth.name': 'Nombre',
    'auth.lastName': 'Apellidos',
    'auth.accountType': 'Tipo de cuenta',
    'auth.particular': 'Particular',
    'auth.business': 'Empresa',
    'auth.termsAgree': 'Acepto los términos y condiciones',
    'auth.loginSuccess': '¡Bienvenido de nuevo!',
    'auth.registerSuccess': '¡Cuenta creada con éxito!',
    'auth.loginError': 'Error al iniciar sesión',
    'auth.registerError': 'Error al crear la cuenta',
    
    // Búsqueda
    'search.title': 'Buscar',
    'search.results': 'resultados',
    'search.noResults': 'No se encontraron resultados',
    'search.tryAgain': 'Intenta con otros términos de búsqueda',
    'search.filters': 'Filtros',
    'search.sortBy': 'Ordenar por',
    'search.newest': 'Más recientes',
    'search.oldest': 'Más antiguos',
    'search.priceLow': 'Precio: menor a mayor',
    'search.priceHigh': 'Precio: mayor a menor',
    'search.priceRange': 'Rango de precio',
    'search.minPrice': 'Precio mínimo',
    'search.maxPrice': 'Precio máximo',
    'search.applyFilters': 'Aplicar filtros',
    'search.clearFilters': 'Limpiar filtros',
    
    // Planes y promociones
    'plans.title': 'Planes de promoción',
    'plans.basic': 'Básico',
    'plans.featured': 'Destacado',
    'plans.premium': 'Premium',
    'plans.vip': 'VIP',
    'plans.free': 'Gratis',
    'plans.perMonth': '/mes',
    'plans.features': 'Características',
    'plans.buy': 'Comprar plan',
    'plans.current': 'Plan actual',
    'plans.upgrade': 'Mejorar plan',
    'plans.remaining': 'días restantes',
    'plans.slots': 'anuncios disponibles',
    
    // Generales
    'general.loading': 'Cargando...',
    'general.error': 'Error',
    'general.success': 'Éxito',
    'general.confirm': 'Confirmar',
    'general.cancel': 'Cancelar',
    'general.delete': 'Eliminar',
    'general.edit': 'Editar',
    'general.save': 'Guardar',
    'general.close': 'Cerrar',
    'general.back': 'Volver',
    'general.next': 'Siguiente',
    'general.previous': 'Anterior',
    'general.seeMore': 'Ver más',
    'general.seeLess': 'Ver menos',
    'general.all': 'Todos',
    'general.none': 'Ninguno',
    'general.yes': 'Sí',
    'general.no': 'No',
    'general.or': 'o',
    'general.and': 'y',
    'general.from': 'desde',
    'general.to': 'hasta',
    'general.free': 'Gratis',
    'general.new': 'Nuevo',
    'general.today': 'Hoy',
    'general.yesterday': 'Ayer',
    'general.daysAgo': 'hace {days} días',
    'general.hoursAgo': 'hace {hours} horas',
    'general.minutesAgo': 'hace {minutes} minutos',
    'general.justNow': 'Ahora mismo',
    
    // Footer
    'footer.about': 'Sobre nosotros',
    'footer.contact': 'Contacto',
    'footer.terms': 'Términos y condiciones',
    'footer.privacy': 'Política de privacidad',
    'footer.cookies': 'Política de cookies',
    'footer.help': 'Centro de ayuda',
    'footer.rights': 'Todos los derechos reservados',
    'footer.downloadApp': '¡Descarga nuestra App!',
    'footer.downloadSubtitle': 'Compra y vende desde cualquier lugar. Disponible en iOS y Android.',
    'footer.downloadOn': 'Descargar en',
    'footer.availableOn': 'Disponible en',
    'footer.downloads': 'Descargas',
    'footer.secure': 'Seguro',
    'footer.brand': 'Nuevo',
    'footer.brandDescription': 'La plataforma líder de compra y venta en España. Conectamos a millones de personas de forma segura y sencilla.',
    'footer.categories': 'Categorías',
    'footer.howToSell': 'Cómo vender',
    'footer.howToBuy': 'Cómo comprar',
    'footer.security': 'Seguridad',
    'footer.legal': 'Legal',
    'footer.termsOfUse': 'Términos de uso',
    'footer.legalNotice': 'Aviso legal',
    'footer.spain': 'España',
    
    // Home page specific
    'home.loadingAds': 'Cargando anuncios...',
    'home.noAdsTitle': 'No hay anuncios disponibles',
    'home.noAdsSubtitle': 'Sé el primero en publicar un anuncio',
    'home.promotedAds': 'Anuncios Promocionados',
    'home.promotedAdsSubtitle': 'Los mejores productos destacados por nuestros vendedores',
    'home.otherAds': 'Otros anuncios',
    'home.moreAds': 'Más anuncios',
    'home.allAds': 'Todos los anuncios',
    'home.ads': 'Anuncios',
    'home.results': 'resultados',
    'home.spain': 'España',
    
    // Ad conditions
    'condition.new': 'Nuevo',
    'condition.likeNew': 'Seminuevo',
    'condition.used': 'Usado',
    
    // Categories
    'category.motor': 'Motor',
    'category.realEstate': 'Inmobiliaria',
    'category.electronics': 'Electrónica',
    'category.fashion': 'Moda',
    'category.home': 'Hogar',
    'category.employment': 'Empleo',
    'category.all': 'Todas las categorías',
    'category.select': 'Selecciona la categoría',
    
    // Notifications
    'notifications.title': 'Notificaciones',
    'notifications.noNotifications': 'No tienes notificaciones',
    'notifications.markRead': 'Marcar leída',
    
    // Dashboard
    'dashboard.overview': 'Panel de control',
    'dashboard.totalAds': 'Total Anuncios',
    'dashboard.totalAdsDesc': 'Todos tus anuncios publicados',
    'dashboard.totalFavorites': 'Total Favoritos',
    'dashboard.totalFavoritesDesc': 'Veces que tus anuncios fueron guardados',
    'dashboard.totalViews': 'Total Visitas',
    'dashboard.totalViewsDesc': 'Visualizaciones de tus anuncios',
    'dashboard.totalSales': 'Total Ventas',
    'dashboard.totalSalesDesc': 'Anuncios marcados como vendidos',
    
    // Sidebar / Profile Menu
    'sidebar.myProfile': 'Mi perfil',
    'sidebar.myAds': 'Mis anuncios',
    'sidebar.promotions': 'Promociones',
    'sidebar.favorites': 'Favoritos',
    'sidebar.messages': 'Mensajes',
    'sidebar.invoices': 'Facturas',
    'sidebar.notifications': 'Notificaciones',
    'sidebar.settings': 'Ajustes',
    'sidebar.help': 'Ayuda',
    'sidebar.logout': 'Cerrar sesión',
    
    // Table Headers
    'table.title': 'Título',
    'table.price': 'Precio',
    'table.status': 'Estado',
    'table.views': 'Vistas',
    'table.actions': 'Acciones',
    'table.date': 'Fecha',
    
    // Actions
    'action.edit': 'Editar',
    'action.delete': 'Eliminar',
    'action.promote': 'Promover',
    'action.view': 'Ver',
    'action.save': 'Guardar',
    'action.cancel': 'Cancelar',
    'action.confirm': 'Confirmar',
    'action.continue': 'Continuar',
    'action.select': 'Seleccionar',
    'action.add': 'Añadir',
    'action.remove': 'Quitar',
    'action.send': 'Enviar',
    'action.reply': 'Responder',
    'action.call': 'Llamar',
    'action.share': 'Compartir',
    'action.report': 'Reportar',
    'action.explore': 'Explorar',
    
    // Errors
    'error.generic': 'Algo salió mal',
    'error.tryAgain': 'Inténtalo de nuevo',
    'error.notFound': 'No encontrado',
    'error.unauthorized': 'No autorizado',
    'error.loginRequired': 'Debes iniciar sesión',
    'error.uploadImage': 'Debes subir al menos una imagen',
    'error.maxImages': 'Máximo 10 imágenes permitidas',
    'error.passwordMismatch': 'Las contraseñas no coinciden',
    'error.passwordShort': 'La contraseña debe tener al menos 6 caracteres',
    'error.publishError': 'Error al publicar el anuncio',
    'error.saveError': 'Error al guardar los cambios',
    'error.loginError': 'Error al iniciar sesión',
    'error.registerError': 'Error al registrarse',
    'error.logoutError': 'Error al cerrar sesión',
    
    // Success
    'success.saved': '¡Guardado correctamente!',
    'success.published': '¡Anuncio publicado!',
    'success.deleted': '¡Eliminado correctamente!',
    'success.passwordChanged': '¡Contraseña actualizada!',
    'success.messageSent': '¡Mensaje enviado!',
    
    // Empty States
    'empty.noAds': 'No tienes anuncios publicados',
    'empty.noFavorites': 'No tienes favoritos',
    'empty.noMessages': 'No tienes mensajes',
    'empty.noNotifications': 'No tienes notificaciones',
    'empty.noResults': 'No hay resultados',
    
    // Promotions
    'promo.title': 'Planes de Promoción',
    'promo.promote': 'Promocionar',
    'promo.buyPromotion': 'Comprar Promoción',
    'promo.rechargeCredits': 'Recargar Créditos',
    'promo.moreViews': '¡Promociona tu anuncio y recibe hasta 15x más visualizaciones!',
    'promo.promoted': 'Promovido',
    'promo.promotedDesc': 'Los anuncios promovidos reciben mayor visibilidad',
    'promo.localOffers': 'Ofertas locales',
    'promo.localOffersDesc': 'Encuentra ofertas cerca de ti',
    'promo.viewPromoted': 'Ver promovidos',
    'promo.clickForPlans': 'Haz clic para ver planes',
    
    // Ad Details
    'adDetail.year': 'Año',
    'adDetail.kilometers': 'Kilómetros',
    'adDetail.transmission': 'Transmisión',
    'adDetail.operation': 'Operación',
    'adDetail.bathrooms': 'Baños',
    'adDetail.rooms': 'Habitaciones',
    'adDetail.gender': 'Género',
    'adDetail.age': 'Edad',
    'adDetail.cover': 'Portada',
    'adDetail.info': 'Información',
    'adDetail.images': 'Imágenes',
    
    // Forms
    'form.required': 'Campo obligatorio',
    'form.optional': 'Opcional',
    'form.name': 'Nombre',
    'form.lastName': 'Apellidos',
    'form.email': 'Email',
    'form.phone': 'Teléfono',
    'form.password': 'Contraseña',
    'form.confirmPassword': 'Confirmar contraseña',
    'form.city': 'Ciudad',
    'form.province': 'Provincia',
    'form.sector': 'Sector',
    'form.selectSector': 'Selecciona un sector',
    'form.companyName': 'Nombre comercial',
    'form.cif': 'CIF/NIF',
    'form.companyDesc': 'Cuéntanos sobre tu empresa...',
    
    // Stats
    'stats.ads': 'Anuncios',
    'stats.rating': 'Rating',
    'stats.views': 'Vistas',
    'stats.sales': 'Ventas',
    
    // Common UI
    'ui.dragDropImages': 'Arrastra tus fotos aquí',
    'ui.orClickSelect': 'o haz clic para seleccionar',
    'ui.loading': 'Cargando...',
    'ui.saving': 'Guardando...',
    'ui.publishing': 'Publicando...',
    
    // Register page specific
    'register.particularDesc': 'Para comprar y vender artículos personales',
    'register.particularFeature1': 'Publica hasta 10 anuncios gratis',
    'register.particularFeature2': 'Contacto directo con compradores',
    'register.particularFeature3': 'Guarda favoritos y alertas',
    'register.createPersonal': 'Crear cuenta personal',
    'register.businessAccount': 'Cuenta Empresa',
    'register.businessDesc': 'Para profesionales y negocios que quieren crecer',
    'register.businessFeature1': 'Anuncios ilimitados',
    'register.businessFeature2': 'Perfil de empresa verificado',
    'register.businessFeature3': 'Estadísticas y análisis',
    'register.businessFeature4': 'Soporte prioritario',
    'register.createBusiness': 'Crear cuenta empresa',
    'register.changeType': 'Cambiar tipo de cuenta',
    'register.professional': 'Cuenta Profesional',
    'register.registerBusiness': 'Registra tu empresa',
    'register.registerBusinessDesc': 'Haz crecer tu negocio con las herramientas profesionales de Vindel',
    'register.representative': 'Representante',
    'register.company': 'Empresa',
    'register.representativeData': 'Datos del representante',
    'register.representativeDesc': 'Persona de contacto de la empresa',
    'register.companyData': 'Datos de la empresa',
    'register.companyInfo': 'Información de tu negocio',
    
    // VIP
    'vip.title': 'Zona VIP',
    'vip.description': 'Contenido exclusivo para usuarios VIP',
    
    // Under construction
    'construction.title': 'En construcción',
    'construction.description': 'Esta página está en desarrollo. ¡Vuelve pronto!',
  },
  
  ro: {
    // Navigare
    'nav.home': 'Acasă',
    'nav.search': 'Caută',
    'nav.publish': 'Publică',
    'nav.messages': 'Mesaje',
    'nav.profile': 'Profil',
    'nav.login': 'Conectare',
    'nav.register': 'Înregistrare',
    'nav.logout': 'Deconectare',
    'nav.favorites': 'Favorite',
    'nav.notifications': 'Notificări',
    'nav.settings': 'Setări',
    'nav.help': 'Ajutor',
    
    // Pagina principală
    'home.hero.title': 'Ce cauți astăzi?',
    'home.hero.subtitle': 'Mii de anunțuri lângă tine',
    'home.search.placeholder': 'Caută mașini, telefoane, apartamente...',
    'home.search.button': 'Caută',
    'home.categories': 'Categorii',
    'home.featured': 'Recomandate',
    'home.recent': 'Cele mai recente',
    'home.viewAll': 'Vezi toate',
    'home.publishFree': 'Publică gratuit',
    
    // Categorii
    'category.imobiliare': 'Imobiliare',
    'category.auto_moto': 'Auto moto',
    'category.locuri_de_munca': 'Locuri de muncă',
    'category.matrimoniale': 'Matrimoniale',
    'category.servicii': 'Servicii',
    'category.electronice': 'Electronice',
    'category.moda_accesorii': 'Modă și accesorii',
    'category.animale': 'Animale',
    'category.casa_gradina': 'Casă și grădină',
    'category.timp_liber_sport': 'Timp liber și sport',
    'category.mama_copil': 'Mama și copilul',
    'category.cazare_turism': 'Cazare turism',
    'category.otros': 'Altele',
    
    // Anunțuri
    'ad.price': 'Preț',
    'ad.negotiable': 'Negociabil',
    'ad.location': 'Locație',
    'ad.published': 'Publicat',
    'ad.views': 'Vizualizări',
    'ad.contact': 'Contactează',
    'ad.sendMessage': 'Trimite mesaj',
    'ad.call': 'Sună',
    'ad.share': 'Distribuie',
    'ad.report': 'Raportează',
    'ad.favorite': 'Favorit',
    'ad.description': 'Descriere',
    'ad.details': 'Detalii',
    'ad.seller': 'Vânzător',
    'ad.condition': 'Stare',
    'ad.condition.new': 'Nou',
    'ad.condition.likeNew': 'Ca nou',
    'ad.condition.used': 'Folosit',
    'ad.delivery': 'Livrare disponibilă',
    'ad.inPerson': 'Vânzare personală',
    'ad.promoted': 'Promovat',
    'ad.featured': 'Recomandat',
    'ad.premium': 'Premium',
    'ad.vip': 'VIP',
    
    // Publică
    'publish.title': 'Publică anunț',
    'publish.titleField': 'Titlul anunțului',
    'publish.titlePlaceholder': 'Ex: iPhone 15 Pro Max 256GB',
    'publish.description': 'Descriere',
    'publish.descriptionPlaceholder': 'Descrie produsul tău în detaliu...',
    'publish.price': 'Preț',
    'publish.pricePlaceholder': 'Preț în €',
    'publish.category': 'Categorie',
    'publish.selectCategory': 'Selectează o categorie',
    'publish.location': 'Locație',
    'publish.locationPlaceholder': 'Oraș sau cod poștal',
    'publish.photos': 'Fotografii',
    'publish.addPhotos': 'Adaugă fotografii',
    'publish.maxPhotos': 'Maximum 10 fotografii',
    'publish.condition': 'Starea produsului',
    'publish.submit': 'Publică anunțul',
    'publish.saving': 'Se publică...',
    'publish.success': 'Anunț publicat cu succes!',
    'publish.error': 'Eroare la publicarea anunțului',
    
    // Profil
    'profile.myProfile': 'Profilul meu',
    'profile.myAds': 'Anunțurile mele',
    'profile.promotions': 'Promoții',
    'profile.favorites': 'Favorite',
    'profile.messages': 'Mesaje',
    'profile.invoices': 'Facturi',
    'profile.settings': 'Setări',
    'profile.edit': 'Editează profil',
    'profile.save': 'Salvează',
    'profile.cancel': 'Anulează',
    'profile.memberSince': 'Membru din',
    'profile.verified': 'Verificat',
    'profile.rating': 'Rating',
    'profile.activeAds': 'Anunțuri active',
    'profile.totalViews': 'Vizualizări totale',
    'profile.totalFavorites': 'Favorite totale',
    'profile.noPlan': 'Fără plan activ',
    'profile.clickForPlans': 'Click pentru a vedea planurile',
    'profile.personalData': 'Date Personale',
    'profile.name': 'Nume',
    'profile.phone': 'Telefon',
    'profile.location': 'Locație',
    'profile.notSpecified': 'Nespecificat',
    'profile.notSpecifiedF': 'Nespecificată',
    'profile.activePromotions': 'Promoțiile Mele Active',
    'profile.daysRemaining': 'rămase',
    'profile.security': 'Securitate',
    'profile.emailVerified': 'Email verificat',
    'profile.active': 'Activ',
    'profile.activate': 'Activează',
    'profile.noActivePromotions': 'Nu ai promoții active',
    'profile.promoteForVisibility': 'Promovează-ți anunțurile pentru mai multă vizibilitate',
    'profile.viewAll': 'Vezi toate',
    'profile.featured': 'Evidențiat',
    'profile.myAccount': 'Contul Meu',
    'profile.manageAccount': 'Gestionează contul, creditele și planurile de promovare',
    'profile.myAdsTitle': 'Anunțurile Mele',
    'profile.published': 'publicate',
    'profile.manageAds': 'Gestionează și promovează anunțurile publicate',
    'profile.myFavorites': 'Favoritele Mele',
    'profile.saved': 'salvate',
    'profile.savedForLater': 'Anunțurile salvate pentru mai târziu',
    'profile.myPromotions': 'Promoțiile Mele',
    'profile.managePromotions': 'Gestionează promoțiile active și impulsionează anunțurile',
    'profile.rechargeCredits': 'Reîncarcă Credite',
    'profile.newAd': 'Anunț nou',
    'profile.promoteAd': 'Promovează Anunț',
    'profile.ads': 'Anunțuri',
    'profile.views': 'Vizualizări',
    'profile.myBalance': 'Soldul Meu',
    'profile.available': 'Disponibil',
    'profile.planType': 'Plan',
    'profile.available2': 'disponibile',
    'profile.businessAccount': 'Cont Companie',
    'profile.total': 'Total',
    'profile.promoted': 'Promovate',
    'profile.adsFound': 'anunțuri găsite',
    'profile.moreViews': 'Mai multe vizualizări',
    'profile.totalSaved': 'Total salvate',
    'profile.totalInvoices': 'Total facturi',
    'profile.totalBilled': 'Total facturat',
    'profile.invoicesTotal': 'facturi în total',
    'profile.invoice': 'factură',
    'profile.totalClaimed': 'Total revendicat',
    'profile.totalPromotions': 'Total Promoții',
    'profile.totalInvestment': 'Investiție Totală',
    'profile.avgIncrease': 'Creștere Medie',
    'profile.promotionStats': 'Statistici promoții',
    'profile.promotionStatsTitle': 'Statisticile Promoției',
    'profile.faster': 'Mai rapid',
    'profile.successRate': 'Rată succes',
    'profile.daysLeft': 'Zile rămase',
    'profile.increase': 'Creștere',
    'profile.sales': 'Vânzări',
    'profile.promotedAds': 'anunțurile promovate au performanță superioară',
    'profile.myPromotedAds': 'Anunțurile Mele Promovate',
    'profile.activePromotion': 'promoție activă',
    'profile.activePromotionsPlural': 'promoții active',
    'profile.ad': 'Anunț',
    'profile.plan': 'Plan',
    'profile.duration': 'Durată',
    'profile.performance': 'Performanță',
    'profile.status': 'Stare',
    'profile.actions': 'Acțiuni',
    'profile.viewsCount': 'vizualizări',
    'profile.daysRemainingTable': 'zile rămase',
    'profile.activeStatus': 'Activ',
    'profile.viewDetails': 'Vezi Detalii',
    'profile.noTitle': 'Fără titlu',
    'profile.noCategory': 'Fără categorie',
    'profile.adsCount': 'anunțuri',
    'profile.adCount': 'anunț',
    'profile.noPromotedAdsYet': 'Nu ai încă anunțuri promovate',
    'profile.promoteAdsDescription': 'Promovează-ți anunțurile pentru a apărea în primele poziții și a ajunge la mai mulți cumpărători',
    'profile.promotionDetails': 'Detaliile Promoției',
    'profile.planTypeLabel': 'Tipul planului',
    'profile.activationDate': 'Data activării',
    'profile.expirationDate': 'Data expirării',
    'profile.totalDuration': 'Durată totală',
    'profile.days': 'zile',
    'profile.searchPriority': 'Prioritate în căutări',
    'profile.maximum': 'Maximă',
    'profile.high': 'Ridicată',
    'profile.medium': 'Medie',
    'profile.visibilityBoost': 'Creștere vizibilitate',
    'profile.activeBenefits': 'Beneficii Active',
    'profile.firstPosition': 'Prima poziție în rezultate',
    'profile.vipLabel': 'Etichetă VIP evidențiată',
    'profile.mainCarousel': 'Apare în caruselul principal',
    'profile.notifyInterested': 'Notificare la interesați',
    'profile.top5Results': 'Top 5 în rezultate',
    'profile.premiumLabel': 'Etichetă Premium',
    'profile.moreVisibility': 'Vizibilitate mai mare',
    'profile.featuredInCategory': 'Evidențiat în categorie',
    'profile.featuredLabel': 'Etichetă Evidențiat',
    'profile.viewAd': 'Vezi Anunțul',
    'profile.close': 'Închide',
    'profile.price': 'Preț',
    'profile.noPromotion': 'Fără promoție',
    'profile.paused': 'Pauză',
    'profile.inReview': 'În revizuire',
    'profile.editAction': 'Editează',
    'profile.viewAction': 'Vezi',
    'profile.deleteAction': 'Șterge',
    'profile.promoteAction': 'Promovează',
    'profile.confirmDelete': 'Ești sigur că vrei să ștergi acest anunț? Această acțiune nu poate fi anulată.',
    'profile.adDeleted': 'Anunț șters',
    'profile.adDeletedDesc': 'Anunțul a fost șters cu succes',
    'profile.errorDeleting': 'Nu s-a putut șterge anunțul',
    'profile.recentlyAdded': 'Adăugate recent',
    'profile.categories': 'Categorii',
    'profile.searchFavorites': 'Caută în favorite...',
    'profile.loadingFavorites': 'Se încarcă favoritele...',
    'profile.noFavoritesYet': 'Nu ai încă favorite',
    'profile.noFavoritesDesc': 'Salvează anunțurile tale favorite pentru a le găsi ușor mai târziu. Apasă pe inimă la orice anunț pentru a-l adăuga aici.',
    'profile.exploreAds': 'Explorează anunțuri',
    'profile.noResults': 'Nu s-au găsit rezultate',
    'profile.noResultsFor': 'Nu există anunțuri care să corespundă cu',
    'profile.clearSearch': 'Șterge căutarea',
    'profile.inPersonSale': 'Vânzare în persoană',
    'profile.recent': 'Recent',
    'profile.myInvoices': 'Facturile Mele',
    'profile.paymentHistory': 'Istoric plăți și facturi',
    'profile.invoiceNumber': 'Nr. Factură',
    'profile.date': 'Dată',
    'profile.concept': 'Descriere',
    'profile.totalAmount': 'Total',
    'profile.paid': 'Plătită',
    'profile.pending': 'În așteptare',
    'profile.cancelled': 'Anulată',
    'profile.viewInvoice': 'Vezi factura',
    'profile.downloadPdf': 'Descarcă PDF',
    'profile.noInvoices': 'Nu ai facturi',
    'profile.noInvoicesDesc': 'Când cumperi un plan de promovare, facturile tale vor apărea aici și le vei putea descărca în PDF.',
    'profile.vatIncluded': 'TVA inclus',
    'profile.invoicesInTotal': 'facturi în total',
    'profile.invoiceInTotal': 'factură în total',
    
    // Setări
    'settings.title': 'Setări',
    'settings.account': 'Cont',
    'settings.notifications': 'Notificări',
    'settings.privacy': 'Confidențialitate',
    'settings.security': 'Securitate',
    'settings.appearance': 'Aspect',
    'settings.help': 'Ajutor',
    'settings.personalInfo': 'Informații personale',
    'settings.updateInfo': 'Actualizează informațiile tale',
    'settings.fullName': 'Nume complet',
    'settings.email': 'Email',
    'settings.phone': 'Telefon',
    'settings.location': 'Locație',
    'settings.companyData': 'Date companie',
    'settings.commercialName': 'Nume comercial',
    'settings.cif': 'CUI/CIF',
    'settings.fiscalAddress': 'Adresă fiscală',
    'settings.website': 'Website',
    'settings.schedule': 'Program',
    'settings.companyDescription': 'Descrierea companiei',
    'settings.dangerZone': 'Zonă periculoasă',
    'settings.deleteAccount': 'Șterge contul',
    'settings.deleteWarning': 'Această acțiune va șterge permanent toate datele tale',
    'settings.changePassword': 'Schimbă parola',
    'settings.currentPassword': 'Parola curentă',
    'settings.newPassword': 'Parola nouă',
    'settings.confirmPassword': 'Confirmă parola',
    'settings.language': 'Limbă',
    'settings.theme': 'Temă',
    'settings.themeLight': 'Luminos',
    'settings.themeDark': 'Întunecat',
    'settings.themeSystem': 'Sistem',
    'settings.manageAccount': 'Gestionează contul și preferințele tale',
    'settings.logout': 'Deconectare',
    'settings.emailNotChange': 'Email-ul nu poate fi schimbat',
    'settings.yourName': 'Numele tău',
    'settings.yourPhone': 'Telefonul tău',
    'settings.yourCity': 'Orașul tău',
    'settings.irreversibleActions': 'Acțiuni ireversibile',
    'settings.delete': 'Șterge',
    'settings.loadingSettings': 'Se încarcă setările...',
    'settings.redirectingLogin': 'Se redirecționează la login...',
    'settings.saved': 'Salvat',
    'settings.save': 'Salvează',
    'settings.businessInfo': 'Informații comerciale despre afacerea ta',
    'settings.companyName': 'Numele companiei tale',
    'settings.emailNotifications': 'Notificări prin email',
    'settings.chooseEmails': 'Alege ce emailuri vrei să primești',
    'settings.newMessages': 'Mesaje noi',
    'settings.newMessagesDesc': 'Primește un email când cineva îți trimite un mesaj',
    'settings.favoritesNotif': 'Favorite',
    'settings.favoritesNotifDesc': 'Notificări despre modificări în anunțurile tale favorite',
    'settings.promotionsNews': 'Promoții și noutăți',
    'settings.promotionsNewsDesc': 'Oferte speciale și actualizări de la VINDEL',
    'settings.pushNotifications': 'Notificări push',
    'settings.pushDesc': 'Notificări pe dispozitivul tău',
    'settings.messages': 'Mesaje',
    'settings.instantNotif': 'Notificări instantanee pentru mesaje noi',
    'settings.favoritesActivity': 'Activitate la favorite',
    'settings.priceAlerts': 'Alerte de scăderi de preț și modificări',
    'settings.sounds': 'Sunete',
    'settings.soundsNotif': 'Sunete de notificare',
    'settings.soundsNotifDesc': 'Redă un sunet când primești notificări',
    'settings.profileVisibility': 'Vizibilitatea profilului',
    'settings.controlInfo': 'Controlează ce informații pot vedea alți utilizatori',
    'settings.publicProfile': 'Profil public',
    'settings.publicProfileDesc': 'Permite altor utilizatori să vadă profilul tău',
    'settings.showPhone': 'Afișează telefonul',
    'settings.showPhoneDesc': 'Afișează numărul tău de telefon în anunțurile tale',
    'settings.showLocation': 'Afișează locația',
    'settings.showLocationDesc': 'Afișează orașul tău în profilul tău',
    'settings.showStats': 'Afișează statisticile',
    'settings.showStatsDesc': 'Afișează public statisticile tale de vânzări',
    'settings.yourData': 'Datele tale',
    'settings.downloadData': 'Descarcă datele mele',
    'settings.downloadDataDesc': 'Obține o copie a tuturor informațiilor tale',
    'settings.download': 'Descarcă',
    'settings.password': 'Parolă',
    'settings.changePasswordDesc': 'Actualizează-ți parola regulat pentru mai multă securitate',
    'settings.change': 'Schimbă',
    'settings.twoFactor': 'Verificare în doi pași',
    'settings.twoFactorAuth': 'Autentificare 2FA',
    'settings.twoFactorDesc': 'Adaugă un nivel suplimentar de securitate contului tău',
    'settings.activate': 'Activează',
    'settings.activeSessions': 'Sesiuni active',
    'settings.thisDevice': 'Acest dispozitiv',
    'settings.lastActivity': 'Ultima activitate: acum',
    'settings.active': 'Activ',
    'settings.themeTitle': 'Temă',
    'settings.themeDesc': 'Selectează aspectul aplicației',
    'settings.light': 'Deschis',
    'settings.dark': 'Întunecat',
    'settings.system': 'Sistem',
    'settings.designStyle': 'Stil de Design',
    'settings.designStyleDesc': 'Alege stilul vizual al întregului site',
    'settings.cardStyle': 'Stil de Carduri',
    'settings.designTip': 'Stilul de design schimbă aspectul cardurilor, categoriilor și elementelor vizuale ale întregului site.',
    'settings.languageDesc': 'Selectează limba ta preferată',
    'settings.helpCenter': 'Centru de ajutor',
    'settings.faq': 'Întrebări frecvente',
    'settings.faqDesc': 'Găsește răspunsuri la cele mai comune întrebări',
    'settings.guides': 'Ghiduri și tutoriale',
    'settings.guidesDesc': 'Învață să profiți la maxim de VINDEL',
    'settings.contactSupport': 'Contactează suportul',
    'settings.contactSupportDesc': 'Ai nevoie de ajutor? Scrie-ne',
    'settings.privacyPolicy': 'Politici de confidențialitate',
    'settings.privacyPolicyDesc': 'Află cum îți protejăm datele',
    'settings.terms': 'Termeni și condiții',
    'settings.termsDesc': 'Citește termenii noștri de serviciu',
    'settings.needHelp': 'Ai nevoie de ajutor?',
    'settings.teamAvailable': 'Echipa noastră este disponibilă 24/7 pentru a te ajuta',
    'settings.chatNow': 'Vorbește acum',
    'settings.deleteAccountQuestion': 'Ștergi contul?',
    'settings.deleteAccountWarning': 'Această acțiune este ireversibilă. Se vor șterge toate anunțurile, mesajele și datele tale personale.',
    'settings.cancel': 'Anulează',
    'settings.changePasswordTitle': 'Schimbă parola',
    'settings.changePasswordSubtitle': 'Introdu parola actuală și cea nouă',
    'settings.passwordUpdated': 'Parolă actualizată!',
    'settings.updatePassword': 'Actualizează parola',
    
    // Mesaje
    'messages.title': 'Mesaje',
    'messages.noMessages': 'Nu ai mesaje',
    'messages.startConversation': 'Începe o conversație',
    'messages.typeMessage': 'Scrie un mesaj...',
    'messages.send': 'Trimite',
    'messages.online': 'Online',
    'messages.offline': 'Offline',
    'messages.lastSeen': 'Ultima dată văzut',
    
    // Autentificare
    'auth.login': 'Conectare',
    'auth.register': 'Înregistrare',
    'auth.email': 'Adresă de email',
    'auth.password': 'Parolă',
    'auth.confirmPassword': 'Confirmă parola',
    'auth.forgotPassword': 'Ai uitat parola?',
    'auth.noAccount': 'Nu ai cont?',
    'auth.hasAccount': 'Ai deja cont?',
    'auth.createAccount': 'Creează cont',
    'auth.name': 'Nume',
    'auth.lastName': 'Prenume',
    'auth.accountType': 'Tip de cont',
    'auth.particular': 'Persoană fizică',
    'auth.business': 'Companie',
    'auth.termsAgree': 'Accept termenii și condițiile',
    'auth.loginSuccess': 'Bine ai revenit!',
    'auth.registerSuccess': 'Cont creat cu succes!',
    'auth.loginError': 'Eroare la conectare',
    'auth.registerError': 'Eroare la crearea contului',
    
    // Căutare
    'search.title': 'Caută',
    'search.results': 'rezultate',
    'search.noResults': 'Nu s-au găsit rezultate',
    'search.tryAgain': 'Încearcă alți termeni de căutare',
    'search.filters': 'Filtre',
    'search.sortBy': 'Sortează după',
    'search.newest': 'Cele mai recente',
    'search.oldest': 'Cele mai vechi',
    'search.priceLow': 'Preț: de la mic la mare',
    'search.priceHigh': 'Preț: de la mare la mic',
    'search.priceRange': 'Interval de preț',
    'search.minPrice': 'Preț minim',
    'search.maxPrice': 'Preț maxim',
    'search.applyFilters': 'Aplică filtre',
    'search.clearFilters': 'Șterge filtre',
    
    // Planuri și promoții
    'plans.title': 'Planuri de promovare',
    'plans.basic': 'Basic',
    'plans.featured': 'Recomandat',
    'plans.premium': 'Premium',
    'plans.vip': 'VIP',
    'plans.free': 'Gratuit',
    'plans.perMonth': '/lună',
    'plans.features': 'Caracteristici',
    'plans.buy': 'Cumpără plan',
    'plans.current': 'Planul curent',
    'plans.upgrade': 'Îmbunătățește planul',
    'plans.remaining': 'zile rămase',
    'plans.slots': 'anunțuri disponibile',
    
    // Generale
    'general.loading': 'Se încarcă...',
    'general.error': 'Eroare',
    'general.success': 'Succes',
    'general.confirm': 'Confirmă',
    'general.cancel': 'Anulează',
    'general.delete': 'Șterge',
    'general.edit': 'Editează',
    'general.save': 'Salvează',
    'general.close': 'Închide',
    'general.back': 'Înapoi',
    'general.next': 'Următorul',
    'general.previous': 'Anterior',
    'general.seeMore': 'Vezi mai mult',
    'general.seeLess': 'Vezi mai puțin',
    'general.all': 'Toate',
    'general.none': 'Niciunul',
    'general.yes': 'Da',
    'general.no': 'Nu',
    'general.or': 'sau',
    'general.and': 'și',
    'general.from': 'de la',
    'general.to': 'până la',
    'general.free': 'Gratuit',
    'general.new': 'Nou',
    'general.today': 'Astăzi',
    'general.yesterday': 'Ieri',
    'general.daysAgo': 'acum {days} zile',
    'general.hoursAgo': 'acum {hours} ore',
    'general.minutesAgo': 'acum {minutes} minute',
    'general.justNow': 'Chiar acum',
    
    // Footer
    'footer.about': 'Despre noi',
    'footer.contact': 'Contact',
    'footer.terms': 'Termeni și condiții',
    'footer.privacy': 'Politica de confidențialitate',
    'footer.cookies': 'Politica de cookies',
    'footer.help': 'Centru de ajutor',
    'footer.rights': 'Toate drepturile rezervate',
    'footer.downloadApp': 'Aplicație Mobilă',
    'footer.downloadSubtitle': 'Ia anunțurile cu tine',
    'footer.downloadOn': 'Descarcă pe',
    'footer.availableOn': 'Disponibil pe',
    'footer.downloads': 'Descărcări',
    'footer.secure': 'Sigur',
    'footer.brand': 'Vindel',
    'footer.brandDescription': 'Platforma lider de cumpărare și vânzare din România. Conectăm milioane de oameni în mod sigur și simplu.',
    'footer.categories': 'Categorii',
    'footer.howToSell': 'Cum să vinzi',
    'footer.howToBuy': 'Cum să cumperi',
    'footer.security': 'Securitate',
    'footer.legal': 'Legal',
    'footer.termsOfUse': 'Termeni de utilizare',
    'footer.legalNotice': 'Aviz legal',
    'footer.spain': 'România',
    
    // Notificaciones
    'notifications.title': 'Notificări',
    'notifications.noNotifications': 'Nu ai notificări',
    'notifications.markRead': 'Marchează ca citită',
    
    // Pagina principală specifică
    'home.loadingAds': 'Se încarcă anunțurile...',
    'home.noAdsTitle': 'Nu există anunțuri disponibile',
    'home.noAdsSubtitle': 'Fii primul care publică un anunț',
    'home.promotedAds': 'Anunțuri Promovate',
    'home.promotedAdsSubtitle': 'Cele mai bune produse evidențiate de vânzătorii noștri',
    'home.otherAds': 'Alte anunțuri',
    'home.moreAds': 'Mai multe anunțuri',
    'home.allAds': 'Toate anunțurile',
    'home.ads': 'Anunțuri',
    'home.results': 'rezultate',
    'home.spain': 'Spania',
    
    // Starea anunțurilor
    'condition.new': 'Nou',
    'condition.likeNew': 'Ca nou',
    'condition.used': 'Folosit',
    
    // Categorii
    'category.motor': 'Motor',
    'category.realEstate': 'Imobiliare',
    'category.electronics': 'Electronice',
    'category.fashion': 'Modă',
    'category.home': 'Casă',
    'category.employment': 'Locuri de muncă',
    
    // Dashboard
    'dashboard.title': 'Panou de control',
    'dashboard.welcome': 'Bine ai venit',
    'dashboard.stats': 'Statistici',
    'dashboard.recentActivity': 'Activitate recentă',
    'dashboard.quickActions': 'Acțiuni rapide',
    
    // Sidebar
    'sidebar.myAds': 'Anunțurile mele',
    'sidebar.promotions': 'Promoții',
    'sidebar.favorites': 'Favorite',
    'sidebar.messages': 'Mesaje',
    'sidebar.invoices': 'Facturi',
    'sidebar.settings': 'Setări',
    'sidebar.help': 'Ajutor',
    'sidebar.logout': 'Deconectare',
    
    // Tabel anunțuri
    'table.photo': 'Fotografie',
    'table.title': 'Titlu',
    'table.price': 'Preț',
    'table.status': 'Stare',
    'table.views': 'Vizualizări',
    'table.date': 'Data',
    'table.actions': 'Acțiuni',
    'table.noData': 'Nu există date',
    'table.loadMore': 'Încarcă mai mult',
    
    // Stări anunțuri
    'status.active': 'Activ',
    'status.inactive': 'Inactiv',
    'status.pending': 'În așteptare',
    'status.sold': 'Vândut',
    'status.reserved': 'Rezervat',
    'status.expired': 'Expirat',
    'status.rejected': 'Respins',
    'status.draft': 'Ciornă',
    
    // Acțiuni
    'action.edit': 'Editează',
    'action.delete': 'Șterge',
    'action.promote': 'Promovează',
    'action.pause': 'Pauză',
    'action.activate': 'Activează',
    'action.duplicate': 'Duplică',
    'action.share': 'Distribuie',
    'action.view': 'Vezi',
    'action.markAsSold': 'Marchează ca vândut',
    'action.renew': 'Reînnoiește',
    'action.boost': 'Impulsionează',
    'action.explore': 'Explorează',
    
    // Mesaje extins
    'messages.deleteConversation': 'Șterge conversația',
    'messages.confirmDelete': 'Sigur vrei să ștergi această conversație?',
    'messages.deleted': 'Conversație ștearsă',
    'messages.newMessage': 'Mesaj nou',
    'messages.unread': 'Necitit',
    'messages.read': 'Citit',
    'messages.sent': 'Trimis',
    'messages.received': 'Primit',
    'messages.writeMessage': 'Scrie un mesaj...',
    'messages.sendMessage': 'Trimite mesaj',
    'messages.noConversations': 'Nu ai conversații',
    'messages.selectConversation': 'Selectează o conversație',
    'messages.you': 'Tu',
    'messages.today': 'Astăzi',
    'messages.yesterday': 'Ieri',
    'messages.block': 'Blochează utilizatorul',
    'messages.report': 'Raportează',
    'messages.archive': 'Arhivează',
    
    // Căutare extins
    'search.whatLooking': 'Ce cauți?',
    'search.searchIn': 'Caută în',
    'search.allCategories': 'Toate categoriile',
    'search.allLocations': 'Toate locațiile',
    'search.min': 'Min',
    'search.max': 'Max',
    'search.apply': 'Aplică',
    'search.reset': 'Resetează',
    'search.showFilters': 'Arată filtre',
    'search.hideFilters': 'Ascunde filtre',
    'search.searchResults': 'Rezultatele căutării',
    'search.foundResults': 'S-au găsit {count} rezultate',
    'search.noResultsFor': 'Nu s-au găsit rezultate pentru "{query}"',
    'search.suggestions': 'Sugestii',
    'search.recentSearches': 'Căutări recente',
    'search.popularSearches': 'Căutări populare',
    'search.clearHistory': 'Șterge istoricul',
    
    // Erori
    'error.generic': 'A apărut o eroare',
    'error.notFound': 'Nu s-a găsit',
    'error.unauthorized': 'Neautorizat',
    'error.forbidden': 'Acces interzis',
    'error.serverError': 'Eroare server',
    'error.networkError': 'Eroare de rețea',
    'error.tryAgain': 'Încearcă din nou',
    'error.goHome': 'Mergi acasă',
    'error.contactSupport': 'Contactează suportul',
    'error.invalidData': 'Date invalide',
    'error.requiredField': 'Câmp obligatoriu',
    'error.invalidEmail': 'Email invalid',
    'error.invalidPhone': 'Telefon invalid',
    'error.passwordTooShort': 'Parola este prea scurtă',
    'error.passwordsNotMatch': 'Parolele nu se potrivesc',
    'error.uploadFailed': 'Încărcarea a eșuat',
    'error.fileTooLarge': 'Fișierul este prea mare',
    'error.invalidFormat': 'Format invalid',
    'error.sessionExpired': 'Sesiunea a expirat',
    'error.loginRequired': 'Trebuie să te conectezi',
    
    // Succese
    'success.saved': 'Salvat cu succes',
    'success.deleted': 'Șters cu succes',
    'success.updated': 'Actualizat cu succes',
    'success.sent': 'Trimis cu succes',
    'success.copied': 'Copiat în clipboard',
    'success.passwordChanged': 'Parolă schimbată',
    'success.profileUpdated': 'Profil actualizat',
    'success.adPublished': 'Anunț publicat',
    'success.adUpdated': 'Anunț actualizat',
    'success.adDeleted': 'Anunț șters',
    'success.messageSent': 'Mesaj trimis',
    'success.addedToFavorites': 'Adăugat la favorite',
    'success.removedFromFavorites': 'Eliminat din favorite',
    
    // Stări goale
    'empty.noAds': 'Nu ai anunțuri',
    'empty.noFavorites': 'Nu ai favorite',
    'empty.noMessages': 'Nu ai mesaje',
    'empty.noNotifications': 'Nu ai notificări',
    'empty.noInvoices': 'Nu ai facturi',
    'empty.noResults': 'Nu s-au găsit rezultate',
    'empty.publishFirst': 'Publică primul tău anunț',
    'empty.startSearching': 'Începe să cauți',
    'empty.startConversation': 'Începe o conversație',
    
    // Promoții
    'promo.promoteAd': 'Promovează anunțul',
    'promo.selectPlan': 'Selectează un plan',
    'promo.currentPlan': 'Planul curent',
    'promo.upgradePlan': 'Îmbunătățește planul',
    'promo.features': 'Caracteristici',
    'promo.moreVisibility': 'Mai multă vizibilitate',
    'promo.topPosition': 'Poziție de top',
    'promo.highlightedAd': 'Anunț evidențiat',
    'promo.socialMedia': 'Promovare pe rețelele sociale',
    'promo.statistics': 'Statistici detaliate',
    'promo.duration': 'Durată',
    'promo.days': 'zile',
    'promo.price': 'Preț',
    'promo.buy': 'Cumpără',
    'promo.active': 'Activ',
    'promo.expired': 'Expirat',
    'promo.remaining': 'Zile rămase',
    
    // Detalii anunț
    'adDetail.contactSeller': 'Contactează vânzătorul',
    'adDetail.makeOffer': 'Fă o ofertă',
    'adDetail.askQuestion': 'Pune o întrebare',
    'adDetail.reportAd': 'Raportează anunțul',
    'adDetail.shareAd': 'Distribuie anunțul',
    'adDetail.similarAds': 'Anunțuri similare',
    'adDetail.sellerInfo': 'Informații vânzător',
    'adDetail.memberSince': 'Membru din',
    'adDetail.responseTime': 'Timp de răspuns',
    'adDetail.responseRate': 'Rată de răspuns',
    'adDetail.lastActive': 'Ultima activitate',
    'adDetail.verifiedSeller': 'Vânzător verificat',
    'adDetail.professionalSeller': 'Vânzător profesionist',
    'adDetail.seeAllAds': 'Vezi toate anunțurile',
    'adDetail.specifications': 'Specificații',
    'adDetail.characteristics': 'Caracteristici',
    
    // Formular
    'form.title': 'Titlu',
    'form.description': 'Descriere',
    'form.price': 'Preț',
    'form.category': 'Categorie',
    'form.subcategory': 'Subcategorie',
    'form.location': 'Locație',
    'form.condition': 'Stare',
    'form.photos': 'Fotografii',
    'form.contact': 'Contact',
    'form.phone': 'Telefon',
    'form.email': 'Email',
    'form.whatsapp': 'WhatsApp',
    'form.showPhone': 'Arată telefonul',
    'form.negotiable': 'Preț negociabil',
    'form.delivery': 'Accept livrare',
    'form.required': 'Obligatoriu',
    'form.optional': 'Opțional',
    'form.minChars': 'Minim {min} caractere',
    'form.maxChars': 'Maximum {max} caractere',
    
    // Statistici
    'stats.totalViews': 'Vizualizări totale',
    'stats.todayViews': 'Vizualizări astăzi',
    'stats.favorites': 'Favorite',
    'stats.messages': 'Mesaje',
    'stats.clicks': 'Clicuri',
    'stats.shares': 'Distribuiri',
    'stats.performance': 'Performanță',
    'stats.views': 'Vizualizări',
    'stats.sales': 'Vânzări',
    
    // UI comun
    'ui.dragDropImages': 'Trage fotografiile aici',
    'ui.orClickSelect': 'sau clic pentru a selecta',
    'ui.loading': 'Se încarcă...',
    'ui.saving': 'Se salvează...',
    'ui.publishing': 'Se publică...',
    
    // Register page specific
    'register.particularDesc': 'Pentru cumpărarea și vânzarea articolelor personale',
    'register.particularFeature1': 'Publică până la 10 anunțuri gratuit',
    'register.particularFeature2': 'Contact direct cu cumpărătorii',
    'register.particularFeature3': 'Salvează favorite și alerte',
    'register.createPersonal': 'Creează cont personal',
    'register.businessAccount': 'Cont Companie',
    'register.businessDesc': 'Pentru profesioniști și afaceri care vor să crească',
    'register.businessFeature1': 'Anunțuri nelimitate',
    'register.businessFeature2': 'Profil de companie verificat',
    'register.businessFeature3': 'Statistici și analize',
    'register.businessFeature4': 'Suport prioritar',
    'register.createBusiness': 'Creează cont de companie',
    'register.changeType': 'Schimbă tipul de cont',
    'register.professional': 'Cont Profesional',
    'register.registerBusiness': 'Înregistrează-ți compania',
    'register.registerBusinessDesc': 'Dezvoltă-ți afacerea cu instrumentele profesionale Vindel',
    'register.representative': 'Reprezentant',
    'register.company': 'Companie',
    'register.representativeData': 'Datele reprezentantului',
    'register.representativeDesc': 'Persoana de contact a companiei',
    'register.companyData': 'Datele companiei',
    'register.companyInfo': 'Informații despre afacerea ta',
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('ro');

  useEffect(() => {
    // Cargar idioma guardado - por defecto rumano
    if (typeof window !== 'undefined') {
      const savedLang = localStorage.getItem('vindel_language') as Language;
      if (savedLang && (savedLang === 'es' || savedLang === 'ro')) {
        setLanguageState(savedLang);
      } else {
        // Por defecto rumano si no hay preferencia guardada
        localStorage.setItem('vindel_language', 'ro');
      }
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('vindel_language', lang);
      // Actualizar el atributo lang del HTML
      document.documentElement.lang = lang;
    }
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

// Hook opcional para traducciones sin contexto (para componentes del servidor)
export function getTranslation(lang: Language, key: string): string {
  return translations[lang][key] || key;
}

// Valor por defecto rumano
export function useLanguage() {
  const context = useContext(LanguageContext);
  // Si no hay provider, devolver valores por defecto para evitar errores
  if (context === undefined) {
    return {
      language: 'ro' as Language,
      setLanguage: () => {},
      t: (key: string) => translations['ro'][key] || key
    };
  }
  return context;
}
